/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleHObjCpp
 */

#import <GooglePlaces/GooglePlaces.h>
#import <React/RCTLog.h>
#import <React/RCTConvert.h>
#import <React/RCTUtils.h>
#import "RCTGooglePlacesSdk.h"

#ifdef RCT_NEW_ARCH_ENABLED
#import "NativeGooglePlacesSdkSpec.h"

@interface RCTGooglePlacesSdk () <NativeGooglePlacesSdkSpec>
@end
#endif

@implementation RCTGooglePlacesSdk

RCT_EXPORT_MODULE(GooglePlacesSdk)

#ifdef RCT_NEW_ARCH_ENABLED
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativeGooglePlacesSdkSpecJSI>(
      params, [self](jsi::Runtime &runtime) { return this; });
}
#endif

@end
